export const Environment = {
    LOG_LEVEL: "LOG_LEVEL",
    APP_ENVIRONMENT: "APP_ENVIRONEMENT",
    DB_CONNECTION_STRING: "DB_CONNECTION_STRING",
    TOKEN_SECRET:"TOKEN_SECRET",
    REFRESH_SECRET:"REFRESH_SECRET"
}